/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NewListingRouteImport } from './routes/new-listing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ListingsSectionRouteImport } from './routes/listings.$section'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewListingRoute = NewListingRouteImport.update({
  id: '/new-listing',
  path: '/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsSectionRoute = ListingsSectionRouteImport.update({
  id: '/listings/$section',
  path: '/listings/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/new-listing': typeof NewListingRoute
  '/notifications': typeof NotificationsRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/listings/$section': typeof ListingsSectionRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/new-listing': typeof NewListingRoute
  '/notifications': typeof NotificationsRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/listings/$section': typeof ListingsSectionRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/new-listing': typeof NewListingRoute
  '/notifications': typeof NotificationsRoute
  '/requests': typeof RequestsRoute
  '/search': typeof SearchRoute
  '/subscribe': typeof SubscribeRoute
  '/listings/$section': typeof ListingsSectionRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/new-listing'
    | '/notifications'
    | '/requests'
    | '/search'
    | '/subscribe'
    | '/listings/$section'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/new-listing'
    | '/notifications'
    | '/requests'
    | '/search'
    | '/subscribe'
    | '/listings/$section'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/new-listing'
    | '/notifications'
    | '/requests'
    | '/search'
    | '/subscribe'
    | '/listings/$section'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  NewListingRoute: typeof NewListingRoute
  NotificationsRoute: typeof NotificationsRoute
  RequestsRoute: typeof RequestsRoute
  SearchRoute: typeof SearchRoute
  SubscribeRoute: typeof SubscribeRoute
  ListingsSectionRoute: typeof ListingsSectionRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-listing': {
      id: '/new-listing'
      path: '/new-listing'
      fullPath: '/new-listing'
      preLoaderRoute: typeof NewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$section': {
      id: '/listings/$section'
      path: '/listings/$section'
      fullPath: '/listings/$section'
      preLoaderRoute: typeof ListingsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  NewListingRoute: NewListingRoute,
  NotificationsRoute: NotificationsRoute,
  RequestsRoute: RequestsRoute,
  SearchRoute: SearchRoute,
  SubscribeRoute: SubscribeRoute,
  ListingsSectionRoute: ListingsSectionRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
